jobs:
  include:
  - name: Syntax check
    language: python
    python: '3.8'
    env:
      - ANSIBLE_ROLES_PATH='../'
    install:
    - pip install ansible
    - ansible --version
    script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check -e 'role_name=bergentroll_role_db'
  - name: Test with Molecule
    language: python
    python: '3.8'
    env:
      - secure: BSoyOTDQxwY4Fsn0JW2JZMi+gcOGOOBW/lRL+q1AHIhKrWvnagpNGikp9xaEUx/7RCwigWbqPGu6Y3ok7HAhQ2Pn8D9hGGo6TTTQE9ykF17w4EoKx1Lfk0CaxMziimkilQh4Pq3OWQH5oFOZw5cFhSlQ4srcj0R1gmdBc0LER1H5n/dosP4ck1iGEFVk9AJCl+qH00rU1woNmu6V7ALhdqXf+K4Sq3IuT5VUqPQiY+2VRPx0vrz9/DAhkU0ciPIEDWtszKg0GsdyPTZf26O0tF6/c69YZQijVP8jfBlLjSI8EMsPpyMEhRsbndxMH+7B64xThjRjwzg/MG95hVhg79QmRGHEDmICVFzfV424277KxWsgA/h70WyhPwi4on1dLQa+Dov5/BKWfpP++JItBBkYAPuCEEJ/mNvO/6b2XoNPC8Re8TcP3b0J7QBlTVwwnV3iaMcV1/eqPoPp4NqMwAxHFBKfHKHD0caBuZ47IMWzaV4zu3AKQ4vqIJj2TvTP2gKDyVp9YOusAF1Pd7PyHnA9sjuDNzOopsrFMWCjjmLbaFdhEVm65lQSGzA7h4yV9CF8PvYrJT9QHy2mgW0pwJ5b7/ZW2DfxEESU7f/+VTfE9Jf1/CQaparDdgV/OHbckak9w48pZaCFUzva2WEiZICovl/MxUppIx+G073TMfM=
      - GCP_SERVICE_ACCOUNT_FILE="${TRAVIS_BUILD_DIR}/credentials.json" 
    before_install:
    - openssl aes-256-cbc -K $encrypted_749dcc9e92f7_key -iv $encrypted_749dcc9e92f7_iv
      -in credentials.json.enc -out credentials.json -d
    install:
    - pip install ansible molecule molecule-gce apache-libcloud google-auth
    - ansible-galaxy collection install google.cloud community.crypto
    script:
    - molecule --debug test
    after_script:
    - molecule --debug destroy
