---

- name: Add MongoDB GPG key
  tags: install
  apt_key:
    id: E162F504A20CDF15827F718D4B7C549A058F8B6B
    keyserver: keyserver.ubuntu.com

- name: Add MongoDB repo
  tags: install
  apt_repository:
    repo: >-
      deb [ arch=amd64,arm64 ]
      https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present

- name: Install MongoDB
  tags: install
  notify: restart mongod
  package:
    name:
      - mongodb-org
    state: latest
    update_cache: true

- name: Change mongo config file
  tags: install
  notify: restart mongod
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644

- name: Enable service
  tags: install
  service:
    name: mongod
    enabled: yes
